# LOAN INTEREST RATE PREDICTION - Model Selection

### Main notebook link: [Click here](Loan-Prediction.ipynb)
By Nohan Joemon

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('../input/analyticsclubproject/train.csv')

## DIFFERENT MODELS:

In [3]:
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

for i in range(7):
    
# KNN
    if i==0: 
        print("\n\n\n",i+1," MODEL : KNN")
        
        # Training the K-NN model on the Training set
        from sklearn.neighbors import KNeighborsClassifier
        classifier = KNeighborsClassifier(n_neighbors = 20, metric = 'minkowski', p = 2)
        classifier.fit(X_train, y_train)
        
        ## Making the Confusion Matrix for train set
        print("\n TRAIN DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_train_pred = classifier.predict(X_train)
        cm_train = confusion_matrix(y_train, y_train_pred)
        print(cm_train)
        print("accuracy score=",accuracy_score(y_train, y_train_pred))

        ## Making the Confusion Matrix for test set
        print("\n TEST DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_test_pred = classifier.predict(X_test)
        cm_test = confusion_matrix(y_test, y_test_pred)
        print(cm_test)
        print("accuracy score=",accuracy_score(y_test, y_test_pred))
    
#Logistic Regression
    elif i==1:
        print("\n\n\n",i+1," MODEL : Logistic Regression")
        
        # Training the Logistic Regression model on the Training set
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train, y_train)
        
        ## Making the Confusion Matrix for train set
        print("\n TRAIN DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_train_pred = classifier.predict(X_train)
        cm_train = confusion_matrix(y_train, y_train_pred)
        print(cm_train)
        print("accuracy score=",accuracy_score(y_train, y_train_pred))

        ## Making the Confusion Matrix for test set
        print("\n TEST DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_test_pred = classifier.predict(X_test)
        cm_test = confusion_matrix(y_test, y_test_pred)
        print(cm_test)
        print("accuracy score=",accuracy_score(y_test, y_test_pred))
    
#Naive Bayes        
    elif i==2: 
        print("\n\n\n",i+1," MODEL : Naive Bayes")
        
        # Training the Naive Bayes model on the Training set
        from sklearn.naive_bayes import GaussianNB
        classifier = GaussianNB()
        classifier.fit(X_train, y_train)

        ## Making the Confusion Matrix for train set
        print("\n TRAIN DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_train_pred = classifier.predict(X_train)
        cm_train = confusion_matrix(y_train, y_train_pred)
        print(cm_train)
        print("accuracy score=",accuracy_score(y_train, y_train_pred))

        ## Making the Confusion Matrix for test set
        print("\n TEST DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_test_pred = classifier.predict(X_test)
        cm_test = confusion_matrix(y_test, y_test_pred)
        print(cm_test)
        print("accuracy score=",accuracy_score(y_test, y_test_pred))
        
#Decision Tree       
    elif i==3: 
        print("\n\n\n",i+1," MODEL : Decision Tree")
        
        # Training the Decision Tree model on the Training set
        from sklearn.tree import DecisionTreeClassifier
        classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        
        ## Making the Confusion Matrix for train set
        print("\n TRAIN DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_train_pred = classifier.predict(X_train)
        cm_train = confusion_matrix(y_train, y_train_pred)
        print(cm_train)
        print("accuracy score=",accuracy_score(y_train, y_train_pred))

        ## Making the Confusion Matrix for test set
        print("\n TEST DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_test_pred = classifier.predict(X_test)
        cm_test = confusion_matrix(y_test, y_test_pred)
        print(cm_test)
        print("accuracy score=",accuracy_score(y_test, y_test_pred))

#Random Forest
    elif i==4: 
        print("\n\n\n",i+1," MODEL : Random Forest")
        
        # Training the Random Forest model on the Training set
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 20, criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        
        ## Making the Confusion Matrix for train set
        print("\n TRAIN DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_train_pred = classifier.predict(X_train)
        cm_train = confusion_matrix(y_train, y_train_pred)
        print(cm_train)
        print("accuracy score=",accuracy_score(y_train, y_train_pred))

        ## Making the Confusion Matrix for test set
        print("\n TEST DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_test_pred = classifier.predict(X_test)
        cm_test = confusion_matrix(y_test, y_test_pred)
        print(cm_test)
        print("accuracy score=",accuracy_score(y_test, y_test_pred))
        
#XGBoost
    elif i==5:
        print("\n\n\n",i+1," MODEL : XGBoost")
        
        # Training the XG Boost model on the Training set
        from xgboost import XGBClassifier
        classifier = XGBClassifier(random_state = 0)
        classifier.fit(X_train, y_train)
        
        ## Making the Confusion Matrix for train set
        print("\n TRAIN DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_train_pred = classifier.predict(X_train)
        cm_train = confusion_matrix(y_train, y_train_pred)
        print(cm_train)
        print("accuracy score=",accuracy_score(y_train, y_train_pred))

        ## Making the Confusion Matrix for test set
        print("\n TEST DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_test_pred = classifier.predict(X_test)
        cm_test = confusion_matrix(y_test, y_test_pred)
        print(cm_test)
        print("accuracy score=",accuracy_score(y_test, y_test_pred))

#MultiLayer Perceptron
    elif i==6: 
        print("\n\n\n",i+1," MODEL : Multilayer Perceptron")
        
        # Training the MLPClassifier model on the Training set
        from sklearn.neural_network import MLPClassifier
        classifier = MLPClassifier(solver="sgd",learning_rate="adaptive", activation="relu",random_state = 0)
        classifier.fit(X_train, y_train)
        
        ## Making the Confusion Matrix for train set
        print("\n TRAIN DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_train_pred = classifier.predict(X_train)
        cm_train = confusion_matrix(y_train, y_train_pred)
        print(cm_train)
        print("accuracy score=",accuracy_score(y_train, y_train_pred))

        ## Making the Confusion Matrix for test set
        print("\n TEST DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_test_pred = classifier.predict(X_test)
        cm_test = confusion_matrix(y_test, y_test_pred)
        print(cm_test)
        print("accuracy score=",accuracy_score(y_test, y_test_pred))
        
#Stochastic Gradient Boosting
    elif i==7: 
        print("\n\n\n",i+1," MODEL : Stochastic Gradient Boosting")
        
        # Training the GradientBoosting Classifier model on the Training set
        from sklearn.ensemble import GradientBoostingClassifier
        classifier = GradientBoostingClassifier(random_state = 0)
        classifier.fit(X_train, y_train)
        
        ## Making the Confusion Matrix for train set
        print("\n TRAIN DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_train_pred = classifier.predict(X_train)
        cm_train = confusion_matrix(y_train, y_train_pred)
        print(cm_train)
        print("accuracy score=",accuracy_score(y_train, y_train_pred))

        ## Making the Confusion Matrix for test set
        print("\n TEST DATA")
        from sklearn.metrics import confusion_matrix, accuracy_score
        y_test_pred = classifier.predict(X_test)
        cm_test = confusion_matrix(y_test, y_test_pred)
        print(cm_test)
        print("accuracy score=",accuracy_score(y_test, y_test_pred))




 1  MODEL : KNN

 TRAIN DATA
[[ 5171 11598  3571]
 [ 3344 29118 10094]
 [ 1413 14453 19823]]
accuracy score= 0.5488867474767967

 TEST DATA
[[1318 4220 1265]
 [1509 8677 3864]
 [ 533 5599 5877]]
accuracy score= 0.4829894711216603



 2  MODEL : Logistic Regression

 TRAIN DATA
[[ 1767 15404  3169]
 [ 1408 30003 11145]
 [  341 16826 18522]]
accuracy score= 0.5101384591976467

 TEST DATA
[[ 633 5095 1075]
 [ 452 9944 3654]
 [ 132 5702 6175]]
accuracy score= 0.5097681212342523



 3  MODEL : Naive Bayes

 TRAIN DATA
[[ 2868 13792  3680]
 [ 2734 29459 10363]
 [  627 18637 16425]]
accuracy score= 0.4945174215144292

 TEST DATA
[[ 974 4570 1259]
 [ 929 9798 3323]
 [ 215 6325 5469]]
accuracy score= 0.4942182459984176



 4  MODEL : Decision Tree

 TRAIN DATA
[[20340     0     0]
 [    0 42556     0]
 [    0     0 35689]]
accuracy score= 1.0

 TEST DATA
[[2043 3030 1730]
 [3167 6293 4590]
 [1753 4753 5503]]
accuracy score= 0.42112470330472884



 5  MODEL : Random Forest

 TRAIN DATA
[[2029

/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[14:22:20] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

 TRAIN DATA


/opt/conda/lib/python3.7/site-packages/xgboost/data.py:114: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "because it will generate extra copies and increase " +


[[ 5821 11862  2657]
 [ 2336 30828  9392]
 [  733 11972 22984]]
accuracy score= 0.6048891819242278

 TEST DATA
[[1409 4399  995]
 [1074 9154 3822]
 [ 326 4796 6887]]
accuracy score= 0.5310084596190129



 7  MODEL : Multilayer Perceptron


/opt/conda/lib/python3.7/site-packages/xgboost/data.py:114: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "because it will generate extra copies and increase " +
/opt/conda/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)



 TRAIN DATA
[[ 3532 13761  3047]
 [ 2631 28177 11748]
 [  623 15043 20023]]
accuracy score= 0.5247451437845514

 TEST DATA
[[1193 4540 1070]
 [ 870 9231 3949]
 [ 244 5053 6712]]
accuracy score= 0.5214533503742925



 8  MODEL : Stochastic Gradient Boosting

 TRAIN DATA
[[ 3025 14267  3048]
 [ 2050 29170 11336]
 [  429 15041 20219]]
accuracy score= 0.5316630319014048

 TEST DATA
[[1036 4719 1048]
 [ 675 9543 3832]
 [ 177 5117 6715]]
accuracy score= 0.5262613352808715


## Result: XGBoost works the best